<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://xin.kuaiqitong.com/c/[1-1]/",34,91);
$z[1][4]=array();
$z[2]=Array("page","http://xin.kuaiqitong.com/plus/view.php?aid=(*)",91,161);
$z[2][4]=array();
$z[3]=Array("titlerule","<h3>[内容]</h3>",161,211);
$z[3][4]=array();
$z[4]=Array("authorrule","达丰财务",211,258);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",258,308);
$z[5][4]=array();
$z[6]=Array("bodyrule","neirong[内容]<!-- 版权 -->",308,369);
$z[6][4]=array();
$z[7]=Array("fyrule","",369,396);
$z[7][4]=array();

?>