<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://www.baitong666.com/zcgs/list_20_[1-14].html",34,107);
$z[1][4]=array();
$z[2]=Array("page","http://www.baitong666.com/zcgs/(*).html",107,169);
$z[2][4]=array();
$z[3]=Array("titlerule"," <h1>[内容]</h1> ",169,221);
$z[3][4]=array();
$z[4]=Array("authorrule","达丰财务",221,268);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",268,318);
$z[5][4]=array();
$z[6]=Array("bodyrule"," <div id=\"articlecontent\">[内容] <div class=\"dede_pages\">\n\n",318,410);
$z[6][4]=array();
$z[7]=Array("fyrule","",410,437);
$z[7][4]=array();

?>