<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://www.gaohangip.com/wiki/11/[1-30]",34,96);
$z[1][4]=array();
$z[2]=Array("page","http://www.gaohangip.com/article/(*).html",96,160);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1><a>[内容]</a></h1>",160,217);
$z[3][4]=array();
$z[4]=Array("authorrule","达丰财务",217,264);
$z[4][4]=array();
$z[5]=Array("sourcerule","来源于网络",264,314);
$z[5][4]=array();
$z[6]=Array("bodyrule","<div class=\"article_content\">[内容]来源：\n",314,392);
$z[6][4]=array();
$z[7]=Array("fyrule","",392,419);
$z[7][4]=array();

?>