
<field:city itemname="城市" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:city>

<field:wordsize itemname="字号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:wordsize>

<field:industry itemname="行业" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:industry>

<field:companytype itemname="企业类型" autofield="1" type="select" isnull="true" default="有限公司,合伙企业"  maxlength="250" page="">
</field:companytype>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="手机号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:now_url itemname="当前页面" autofield="1" type="textchar" isnull="true" default=""  maxlength="250" page="">
</field:now_url>

