<dd class="recommend"> <img src="/templets/default/css/120915539469.jpg">
                      <div class="recomt"><a href="[field:arcurl /]" target="_blank">[field:title /]</a>
                          <!--<em>[field:pubdate function="GetDateMK(@me)"/]</em> -->
                      </div>
			      <div class="recomdeail">　　[field:description function='cn_substr(Html2text("@me")."...",160)'/]...</div>
			      <div class="more"><a href="[field:arcurl /]" target="_blank">[ 详情 ]</a></div>
		        </dd>