<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://www.baitong666.com/news/list_3_[1-21].html",34,106);
$z[1][4]=array();
$z[2]=Array("page","http://www.baitong666.com/news/(*).html",106,168);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1>[内容]</h1>",168,218);
$z[3][4]=array();
$z[4]=Array("authorrule","达丰财务",218,265);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",265,315);
$z[5][4]=array();
$z[6]=Array("bodyrule","<div id=\"articlecontent\">[内容] <div class=\"dede_pages\">",315,404);
$z[6][4]=array();
$z[7]=Array("fyrule","",404,431);
$z[7][4]=array();

?>