<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://www.qibangbang.com/article/list_3_[1-157].html",34,110);
$z[1][4]=array();
$z[2]=Array("page","http://www.qibangbang.com/article/detail_(*).html",110,182);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1>[内容]</h1>",182,232);
$z[3][4]=array();
$z[4]=Array("authorrule","达丰财务",232,279);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",279,329);
$z[5][4]=array();
$z[6]=Array("bodyrule","<div class=\"art_box_dy ft14\">[内容]<div class=\"qbb_art_botadd\">\n",329,426);
$z[6][4]=array();
$z[7]=Array("fyrule","",426,453);
$z[7][4]=array();

?>