<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://xin.kuaiqitong.com/c/1/",34,87);
$z[1][4]=array();
$z[2]=Array("page","http://xin.kuaiqitong.com/plus/view.php?aid=(*)",87,157);
$z[2][4]=array();
$z[3]=Array("titlerule"," <h3>[内容]</h3>\n",157,209);
$z[3][4]=array();
$z[4]=Array("authorrule","达丰财务",209,256);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",256,306);
$z[5][4]=array();
$z[6]=Array("bodyrule","热度：<script src=\"/plus/count.php?view=yes&aid=190&mid=1\" type='text/javascript' language=\"javascript\"></script></font></p>\n[内容]<!-- 版权 -->\n\n\n",306,491);
$z[6][4]=array();
$z[7]=Array("fyrule","",491,518);
$z[7][4]=array();

?>