<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://www.zizhiguanjia.com/zs/pn[1-30]/",34,97);
$z[1][4]=array();
$z[2]=Array("page","http://www.zizhiguanjia.com/zs/(*).html",97,159);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1>[内容]</h1>",159,209);
$z[3][4]=array();
$z[4]=Array("authorrule","",209,244);
$z[4][4]=array();
$z[5]=Array("sourcerule","",244,279);
$z[5][4]=array();
$z[6]=Array("bodyrule","<!-- 文章内容 -->[内容]相关推荐：",279,354);
$z[6][4]=array();
$z[7]=Array("fyrule","",354,381);
$z[7][4]=array();

?>