<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://www.qibangbang.com/article/list_[0-11]_[1-157].html",34,115);
$z[1][4]=array();
$z[2]=Array("page","http://www.qibangbang.com/article/detail_(*).html",115,187);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1 class=\"h1\">[内容]</h1>",187,248);
$z[3][4]=array();
$z[4]=Array("authorrule","达丰财务",248,295);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",295,345);
$z[5][4]=array();
$z[6]=Array("bodyrule","<div class=\"art_box_dy ft14\">[内容]<div class=\"qbb_art_botadd\">",345,441);
$z[6][4]=array();
$z[7]=Array("fyrule","",441,468);
$z[7][4]=array();

?>