<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","https://www.huisuanzhang.com/caishui_[1-8].html",34,104);
$z[1][4]=array();
$z[2]=Array("page","https://www.huisuanzhang.com/news/(*).html",104,169);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1>[内容]</h1>",169,219);
$z[3][4]=array();
$z[4]=Array("authorrule","河南达丰财务",219,272);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",272,322);
$z[5][4]=array();
$z[6]=Array("bodyrule","<div id=\"content1\" >[内容]<div class=\"superaddition\">",322,408);
$z[6][4]=array();
$z[7]=Array("fyrule","",408,435);
$z[7][4]=array();

?>