<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","https://www.huisuanzhang.com/caishui_[1-8].html",34,104);
$z[1][4]=array();
$z[2]=Array("page","",104,127);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1>[内容]</h1>",127,177);
$z[3][4]=array();
$z[4]=Array("authorrule","河南达丰财务",177,230);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",230,280);
$z[5][4]=array();
$z[6]=Array("bodyrule","<div id=\"content1\" >[内容]<div class=\"superaddition\">",280,366);
$z[6][4]=array();
$z[7]=Array("fyrule","",366,393);
$z[7][4]=array();

?>