<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://www.qkb2018.com/news/index_[1-55].html",34,102);
$z[1][4]=array();
$z[2]=Array("page","http://www.qkb2018.com/news/dailijizhang/(*).html",102,174);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1>[内容]</h1>",174,224);
$z[3][4]=array();
$z[4]=Array("authorrule","河南达丰财务",224,277);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",277,327);
$z[5][4]=array();
$z[6]=Array("bodyrule"," <div id=\"content1\" >[内容]<div class=\"superaddition\">",327,414);
$z[6][4]=array();
$z[7]=Array("fyrule","",414,441);
$z[7][4]=array();

?>