<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://www.baitong666.com/faq/list_4_[1-12].html",34,105);
$z[1][4]=array();
$z[2]=Array("page","",105,128);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1>[内容]</h1>",128,178);
$z[3][4]=array();
$z[4]=Array("authorrule","达丰财务",178,225);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",225,275);
$z[5][4]=array();
$z[6]=Array("bodyrule"," <div id=\"articlecontent\">[内容]<div class=\"dede_pages\">\n",275,365);
$z[6][4]=array();
$z[7]=Array("fyrule","",365,392);
$z[7][4]=array();

?>