
<field:xm itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xm>

<field:dianhua itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dianhua>

<field:xuqiu itemname="需求" autofield="1" type="select" isnull="true" default="请选择,工商服务,做账报税,内帐整理,商标注册,竞价托管,网站建设"  maxlength="250" page="">
</field:xuqiu>

<field:lynr itemname="留言内容" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lynr>
