<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://www.lvzheng.com/xiaoweishuo/bjdljz?pageno=[1-10]",34,112);
$z[1][4]=array();
$z[2]=Array("page","http://www.lvzheng.com/xiaoweishuo/(*).html",112,178);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1>[内容]</h1>",178,228);
$z[3][4]=array();
$z[4]=Array("authorrule","河南达丰财务",228,281);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",281,331);
$z[5][4]=array();
$z[6]=Array("bodyrule","<span>阅读 [内容]<div class=\"blog-menu\">",331,406);
$z[6][4]=array();
$z[7]=Array("fyrule","",406,433);
$z[7][4]=array();

?>