<?php
$z[0]=Array("charset","utf-8",0,34);
$z[0][4]=array();
$z[1]=Array("list","http://www.zhuojiaipr.com/h-col-114.html",34,97);
$z[1][4]=array();
$z[2]=Array("page","http://www.zhuojiaipr.com/h-nd-(*).html#_np=114_1312",97,172);
$z[2][4]=array();
$z[3]=Array("titlerule","<h1 class='title'>[内容]</h1>\n",172,237);
$z[3][4]=array();
$z[4]=Array("authorrule","河南达丰财务",237,290);
$z[4][4]=array();
$z[5]=Array("sourcerule","整理自网络",290,340);
$z[5][4]=array();
$z[6]=Array("bodyrule","<div class='richContent  richContent0'>[内容]<div class='line2'>",340,437);
$z[6][4]=array();
$z[7]=Array("fyrule","",437,464);
$z[7][4]=array();

?>