<?php
$z[0]=Array("channelartlist","\r\n					<dd><a href=\"{dede:field name='typeurl'/}\" target=\"_blank\">{dede:field name='typename'/}</a></dd>\r\n						",2695,2882);
$z[0][4]=array();
$z[0][4]['typeid']="4,5,6,7,8";
$z[1]=Array("channel","\r\n					<dd><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dd>\r\n					",2954,3091);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['typeid']="22";
$z[2]=Array("channelartlist","\r\n					<dd><a href=\"{dede:field name='typeurl'/}\" target=\"_blank\">{dede:field name='typename'/}</a></dd>\r\n					",3162,3344);
$z[2][4]=array();
$z[2][4]['typeid']="1,2,3";

?>