<?php
$z[0]=Array("type","\r\n					<a href=\"list.php?tid=[field:id/]\" target=\"_blank\">[field:typename/]</a>\r\n                     ",302,438);
$z[0][4]=array();
$z[0][4]['typeid']="4";
$z[1]=Array("channel","\r\n						<span><a href=\"list.php?tid=[field:id/]\" target=\"_blank\">[field:typename/]</a></span>\r\n						  ",485,637);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['typeid']="4";
$z[2]=Array("type","\r\n				<li><a href=\"list.php?tid=[field:id/]\" target=\"_blank\">[field:typename/]</a></li>\r\n				 ",682,810);
$z[2][4]=array();
$z[2][4]['typeid']="5";
$z[3]=Array("type","\r\n				<li><a href=\"list.php?tid=[field:id/]\" target=\"_blank\">[field:typename/]</a></li>\r\n				 ",828,956);
$z[3][4]=array();
$z[3][4]['typeid']="6";
$z[4]=Array("type","\r\n				<li><a href=\"list.php?tid=[field:id/]\" target=\"_blank\">[field:typename/]</a></li>\r\n				 ",975,1103);
$z[4][4]=array();
$z[4][4]['typeid']="7";
$z[5]=Array("type","\r\n				<li><a href=\"list.php?tid=[field:id/]\" target=\"_blank\">[field:typename/]</a></li>\r\n				 ",1123,1251);
$z[5][4]=array();
$z[5][4]['typeid']="8";
$z[6]=Array("type","\r\n											<li><a href=\"list.php?tid=[field:id/]\" target=\"_blank\">[field:typename/] </a></li>\r\n                                            ",1821,1996);
$z[6][4]=array();
$z[6][4]['typeid']="1";
$z[7]=Array("type","\r\n											<li><a href=\"list.php?tid=[field:id/]\" target=\"_blank\">[field:typename/] </a></li>\r\n                                            ",2042,2217);
$z[7][4]=array();
$z[7][4]['typeid']="2";
$z[8]=Array("type","\r\n											<li><a href=\"list.php?tid=[field:id/]\" target=\"_blank\">[field:typename/] </a></li>\r\n                                            ",2263,2438);
$z[8][4]=array();
$z[8][4]['typeid']="3";
$z[9]=Array("global","",2552,2573);
$z[9][4]=array();
$z[9][4]['name']="cfg_qq";

?>