<?php
$z[0]=Array("type","\r\n									<dt><a href=\"[field:typeurl/]\" target=\"_blank\"><em></em></a><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dt>\r\n                                ",91,299);
$z[0][4]=array();
$z[0][4]['typeid']="4";
$z[1]=Array("channel","\r\n																				<a href=\"[field:typeurl/]\" target=\"_blank\"> [field:typename/] </a>&nbsp;\r\n																			    ",396,564);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['typeid']="4";
$z[2]=Array("type","\r\n									<dt><a href=\"[field:typeurl/]\" target=\"_blank\"><em></em></a><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dt>\r\n                                ",776,984);
$z[2][4]=array();
$z[2][4]['typeid']="5";
$z[3]=Array("channel","\r\n																				<a href=\"[field:typeurl/]\" target=\"_blank\"> [field:typename/] </a>&nbsp;\r\n																			    ",1081,1249);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['typeid']="5";
$z[4]=Array("type","\r\n									<dt><a href=\"[field:typeurl/]\" target=\"_blank\"><em></em></a><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dt>\r\n                                ",1401,1609);
$z[4][4]=array();
$z[4][4]['typeid']="6";
$z[5]=Array("channel","\r\n																				<a href=\"[field:typeurl/]\" target=\"_blank\"> [field:typename/] </a>&nbsp;\r\n																			    ",1706,1874);
$z[5][4]=array();
$z[5][4]['type']="son";
$z[5][4]['typeid']="6";
$z[6]=Array("type","\r\n									<dt><a href=\"[field:typeurl/]\" target=\"_blank\"><em></em></a><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dt>\r\n                                ",2026,2234);
$z[6][4]=array();
$z[6][4]['typeid']="7";
$z[7]=Array("channel","\r\n																				<a href=\"[field:typeurl/]\" target=\"_blank\"> [field:typename/] </a>&nbsp;\r\n																			    ",2331,2499);
$z[7][4]=array();
$z[7][4]['type']="son";
$z[7][4]['typeid']="7";
$z[8]=Array("type","\r\n									<dt><a href=\"[field:typeurl/]\" target=\"_blank\"><em></em></a><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dt>\r\n                                ",2651,2859);
$z[8][4]=array();
$z[8][4]['typeid']="8";
$z[9]=Array("channel","\r\n																				<a href=\"[field:typeurl/]\" target=\"_blank\"> [field:typename/] </a>&nbsp;\r\n																			    ",2956,3124);
$z[9][4]=array();
$z[9][4]['type']="son";
$z[9][4]['typeid']="8";

?>