<?php
$z[0]=Array("type","\n									<dt><a href=\"[field:typeurl/]\" target=\"_blank\"><em></em></a><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dt>\n                                ",89,295);
$z[0][4]=array();
$z[0][4]['typeid']="4";
$z[1]=Array("channel","\n																				<a href=\"[field:typeurl/]\" target=\"_blank\"> [field:typename/] </a>&nbsp;\n																			    ",390,556);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['typeid']="4";
$z[2]=Array("type","\n									<dt><a href=\"[field:typeurl/]\" target=\"_blank\"><em></em></a><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dt>\n                                ",760,966);
$z[2][4]=array();
$z[2][4]['typeid']="5";
$z[3]=Array("channel","\n																				<a href=\"[field:typeurl/]\" target=\"_blank\"> [field:typename/] </a>&nbsp;\n																			    ",1061,1227);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['typeid']="5";
$z[4]=Array("type","\n									<dt><a href=\"[field:typeurl/]\" target=\"_blank\"><em></em></a><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dt>\n                                ",1373,1579);
$z[4][4]=array();
$z[4][4]['typeid']="6";
$z[5]=Array("channel","\n																				<a href=\"[field:typeurl/]\" target=\"_blank\"> [field:typename/] </a>&nbsp;\n																			    ",1674,1840);
$z[5][4]=array();
$z[5][4]['type']="son";
$z[5][4]['typeid']="6";
$z[6]=Array("type","\n									<dt><a href=\"[field:typeurl/]\" target=\"_blank\"><em></em></a><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dt>\n                                ",1986,2192);
$z[6][4]=array();
$z[6][4]['typeid']="7";
$z[7]=Array("channel","\n																				<a href=\"[field:typeurl/]\" target=\"_blank\"> [field:typename/] </a>&nbsp;\n																			    ",2287,2453);
$z[7][4]=array();
$z[7][4]['type']="son";
$z[7][4]['typeid']="7";
$z[8]=Array("type","\n									<dt><a href=\"[field:typeurl/]\" target=\"_blank\"><em></em></a><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></dt>\n                                ",2599,2805);
$z[8][4]=array();
$z[8][4]['typeid']="8";
$z[9]=Array("channel","\n																				<a href=\"[field:typeurl/]\" target=\"_blank\"> [field:typename/] </a>&nbsp;\n																			    ",2900,3066);
$z[9][4]=array();
$z[9][4]['type']="son";
$z[9][4]['typeid']="8";

?>