<?php
$z[0]=Array("type","\r\n											<li><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/] </a></li>\r\n                                            ",148,315);
$z[0][4]=array();
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n											<li><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/] </a></li>\r\n                                            ",361,528);
$z[1][4]=array();
$z[1][4]['typeid']="2";
$z[2]=Array("type","\r\n											<li><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/] </a></li>\r\n                                            ",574,741);
$z[2][4]=array();
$z[2][4]['typeid']="3";

?>